#!/bin/bash
set -e

sudo chown root:root /bin/start_mission.sh
sudo chown root:root /bin/stop_mission.sh
sudo chown root:root /etc/systemd/system/mission.service
sudo docker load -i /tmp/night_lines.tar.gz
sudo rm -rf /tmp/night_lines.tar.gz
sudo systemctl enable mission.service

sudo nmcli c reload
