version: "3.3"

services:
  sitl:
    build:
      context: ${PWD}
      dockerfile: docker/dockerfiles/sitl.dockerfile
    container_name: sitl
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - sitl_eeprom_cache:/ardupilot/eeprom.bin
    environment:
      - DISPLAY=${DISPLAY}
    privileged: true
    stdin_open: true
    tty: true
    command:
      [
        "sim_vehicle.py",
        "-v",
        "ArduCopter",
        "--map",
        "--console",
        "--no-rebuild",
        "--no-extra-ports",
        "--out=mission_planner:14550",
        "-l",
        "31.4993848,34.8041511,0,0"
      ]
    networks: 
      - dev

  mission_planner:
    build:
      context: ${PWD}
      dockerfile: docker/dockerfiles/mission_planner.dockerfile
    container_name: mission_planner
    environment: 
      - DISPLAY=${DISPLAY}
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  sitl_eeprom_cache:
